//! SQLite backend for voidm using the generic Database trait
//!
//! This crate provides a lightweight SQLite backend implementation
//! that uses the QueryTranslator abstraction from voidm-core for all SQL generation.
//!
//! Key pattern: JSON ↔ CypherOperation ↔ SQL Translation
//! - Incoming JSON trait calls converted to CypherOperation
//! - SqliteTranslator generates backend-specific SQL
//! - Results converted back to JSON for trait consumers

use anyhow::{Context, Result};
use chrono::Utc;
use once_cell::sync::OnceCell;
use serde_json::{json, Value};
use sqlx::sqlite::{SqliteConnectOptions, SqlitePool, SqlitePoolOptions, SqliteRow};
use sqlx::{FromRow, Row};
use std::path::Path;
use std::pin::Pin;
use std::future::Future;
use std::str::FromStr;
use uuid::Uuid;
use tracing;
use voidm_db_trait::Database;
use voidm_core::query::translator::QueryTranslator;
use voidm_core::query::sqlite::SqliteTranslator;
use voidm_core::query::cypher::CypherOperation;

/// Load sqlite-vec at process level via sqlite3_auto_extension
fn ensure_sqlite_vec_loaded() {
    static LOADED: OnceCell<()> = OnceCell::new();
    LOADED.get_or_init(|| unsafe {
        libsqlite3_sys::sqlite3_auto_extension(Some(std::mem::transmute(
            sqlite_vec::sqlite3_vec_init as *const (),
        )));
    });
}

/// Open or create SQLite connection pool
pub async fn open_pool(db_path: &Path) -> Result<SqlitePool> {
    ensure_sqlite_vec_loaded();

    if let Some(parent) = db_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Cannot create directory {}", parent.display()))?;
    }

    let url = format!("sqlite://{}?mode=rwc", db_path.display());
    let opts = SqliteConnectOptions::from_str(&url)?
        .journal_mode(sqlx::sqlite::SqliteJournalMode::Wal)
        .foreign_keys(true)
        .create_if_missing(true);

    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect_with(opts)
        .await
        .with_context(|| format!("Cannot open database at {}", db_path.display()))?;

    // Initialize schema
    let db = SqliteDatabase::new(pool.clone());
    db.ensure_schema().await?;

    Ok(pool)
}

/// SQLite database backend using generic Database trait
#[derive(Clone)]
pub struct SqliteDatabase {
    pub pool: SqlitePool,
}

impl SqliteDatabase {
    /// Create new instance with existing pool
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    /// Get the query translator
    fn translator() -> SqliteTranslator {
        SqliteTranslator
    }

    /// Execute a query generated by translator and map to JSON
    async fn execute_and_map<F>(
        &self,
        sql: &str,
        params: &voidm_core::query::QueryParams,
        map_fn: F,
    ) -> Result<Value>
    where
        F: Fn(&SqliteRow) -> Value,
    {
        // This is a simplified version - full implementation would use sqlx bind parameters
        let row = sqlx::query(sql)
            .fetch_optional(&self.pool)
            .await
            .context("Query execution failed")?;

        Ok(row.map(|r| map_fn(&r)).unwrap_or(Value::Null))
    }
}

impl Database for SqliteDatabase {
    fn health_check(&self) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            sqlx::query("SELECT 1").execute(&pool).await?;
            Ok(())
        })
    }

    fn close(&self) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            pool.close().await;
            Ok(())
        })
    }

    fn ensure_schema(&self) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            // Use voidm_core::migrate to run the complete schema
            // This ensures all tables and migrations are applied properly
            voidm_core::migrate::run(&pool).await?;
            Ok(())
        })
    }

    fn add_memory(
        &self,
        req_json: Value,
        config_json: &Value,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let config_json = config_json.clone();
        Box::pin(async move {
            // Deserialize request and config
            let req: voidm_core::models::AddMemoryRequest = serde_json::from_value(req_json)
                .context("Failed to parse AddMemoryRequest")?;
            let config: voidm_core::Config = serde_json::from_value(config_json)
                .context("Failed to parse Config")?;
            
            // Call the real implementation
            let resp = voidm_core::crud::add_memory(&pool, req, &config).await?;
            
            // Serialize response with proper field name "type" (not "memory_type")
            Ok(serde_json::json!({
                "id": resp.id,
                "type": resp.memory_type,
                "content": resp.content,
                "scopes": resp.scopes,
                "tags": resp.tags,
                "importance": resp.importance,
                "created_at": resp.created_at,
                "quality_score": resp.quality_score,
                "context": resp.context,
                "title": resp.title,
                "suggested_links": resp.suggested_links,
                "duplicate_warning": resp.duplicate_warning,
            }))
        })
    }

    fn get_memory(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<Option<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            match voidm_core::crud::get_memory(&pool, &id).await {
                Ok(Some(mem)) => Ok(Some(serde_json::to_value(mem)?)),
                Ok(None) => Ok(None),
                Err(e) => Err(e),
            }
        })
    }

    fn list_memories(
        &self,
        limit: Option<usize>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            match voidm_core::crud::list_memories(&pool, None, None, limit.unwrap_or(100)).await {
                Ok(mems) => Ok(mems.into_iter().map(|m| serde_json::to_value(m).unwrap_or(Value::Null)).collect()),
                Err(e) => Err(e),
            }
        })
    }

    fn delete_memory(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            voidm_core::crud::delete_memory(&pool, &id).await
        })
    }

    fn update_memory(
        &self,
        id: &str,
        content: &str,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        let content = content.to_string();
        Box::pin(async move {
            let now = Utc::now().to_rfc3339();
            sqlx::query("UPDATE memories SET content = ?, updated_at = ? WHERE id = ? OR id LIKE ?")
                .bind(&content)
                .bind(&now)
                .bind(&id)
                .bind(format!("{}%", id))
                .execute(&pool)
                .await
                .context("Failed to update memory")?;
            Ok(())
        })
    }

    fn resolve_memory_id(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<String>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            if id.len() < 4 {
                anyhow::bail!("ID prefix too short");
            }
            let row = sqlx::query_scalar::<_, String>("SELECT id FROM memories WHERE id LIKE ? LIMIT 1")
                .bind(format!("{}%", id))
                .fetch_optional(&pool)
                .await
                .context("Failed to resolve ID")?;

            row.context("ID not found")
        })
    }

    fn list_scopes(&self) -> Pin<Box<dyn Future<Output = Result<Vec<String>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query_scalar::<_, String>(
                "SELECT DISTINCT scope FROM (SELECT json_each.value as scope FROM memories, json_each(memories.scopes))"
            )
            .fetch_all(&pool)
            .await
            .unwrap_or_default();
            Ok(rows)
        })
    }

    // ===== Memory Edges =====

    fn link_memories(
        &self,
        from_id: &str,
        rel: &str,
        to_id: &str,
        note: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let rel = rel.to_string();
        let to_id = to_id.to_string();
        let note = note.map(|s| s.to_string());
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            let id = Uuid::new_v4().to_string();
            sqlx::query(
                "INSERT OR REPLACE INTO memory_edges (id, from_id, rel_type, to_id, note, created_at) VALUES (?, ?, ?, ?, ?, ?)",
            )
            .bind(&id)
            .bind(&from_id)
            .bind(&rel)
            .bind(&to_id)
            .bind(&note)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to link memories")?;

            // Return proper LinkResponse struct matching voidm-core::models::LinkResponse
            let response = serde_json::json!({
                "created": true,
                "from": from_id,
                "rel": rel,
                "to": to_id,
                "conflict_warning": serde_json::Value::Null
            });
            Ok(response)
        })
    }

    fn unlink_memories(
        &self,
        from_id: &str,
        rel: &str,
        to_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let rel = rel.to_string();
        let to_id = to_id.to_string();

        Box::pin(async move {
            let result = sqlx::query("DELETE FROM memory_edges WHERE from_id = ? AND rel_type = ? AND to_id = ?")
                .bind(&from_id)
                .bind(&rel)
                .bind(&to_id)
                .execute(&pool)
                .await
                .context("Failed to unlink memories")?;

            Ok(result.rows_affected() > 0)
        })
    }

    fn list_edges(&self) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query("SELECT id, from_id, rel_type, to_id, note FROM memory_edges")
                .fetch_all(&pool)
                .await
                .context("Failed to list edges")?;

            Ok(rows.iter().map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "from_id": r.get::<String, _>("from_id"),
                    "rel_type": r.get::<String, _>("rel_type"),
                    "to_id": r.get::<String, _>("to_id"),
                    "note": r.get::<Option<String>, _>("note")
                })
            }).collect())
        })
    }

    fn list_ontology_edges(&self) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query("SELECT id, from_id, from_type, rel_type, to_id, to_type, note FROM ontology_edges")
                .fetch_all(&pool)
                .await
                .context("Failed to list ontology edges")?;

            Ok(rows.iter().map(|r| {
                json!({
                    "id": r.get::<i64, _>("id"),
                    "from_id": r.get::<String, _>("from_id"),
                    "from_type": r.get::<String, _>("from_type"),
                    "rel_type": r.get::<String, _>("rel_type"),
                    "to_id": r.get::<String, _>("to_id"),
                    "to_type": r.get::<String, _>("to_type"),
                    "note": r.get::<Option<String>, _>("note")
                })
            }).collect())
        })
    }

    fn create_ontology_edge(
        &self,
        from_id: &str,
        from_type: &str,
        rel_type: &str,
        to_id: &str,
        to_type: &str,
    ) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let from_type = from_type.to_string();
        let rel_type = rel_type.to_string();
        let to_id = to_id.to_string();
        let to_type = to_type.to_string();
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            sqlx::query(
                "INSERT INTO ontology_edges (from_id, from_type, rel_type, to_id, to_type, created_at) VALUES (?, ?, ?, ?, ?, ?)",
            )
            .bind(&from_id)
            .bind(&from_type)
            .bind(&rel_type)
            .bind(&to_id)
            .bind(&to_type)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to create ontology edge")?;

            Ok(true)
        })
    }

    // ===== Search Stubs (for now) =====

    fn search_bm25(
        &self,
        query: &str,
        scope_filter: Option<&str>,
        type_filter: Option<&str>,
        limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, f32)>>> + Send + '_>> {
        let pool = self.pool.clone();
        let query_str = query.to_string();
        let scope_filter = scope_filter.map(|s| s.to_string());
        let type_filter = type_filter.map(|s| s.to_string());

        Box::pin(async move {
            // Query FTS5 using raw query to avoid type serialization issues
            let fts_sql = "
                SELECT id, bm25(memories_fts) as bm25_score
                FROM memories_fts
                WHERE memories_fts MATCH ?
                ORDER BY bm25_score DESC
                LIMIT ?
            ";

            // Use raw query to manually deserialize
            let rows = sqlx::query(fts_sql)
                .bind(&query_str)
                .bind((limit * 2) as i64)
                .fetch_all(&pool)
                .await?;

            let mut results: Vec<(String, f32)> = Vec::new();
            
            for row in rows {
                let id: String = row.try_get("id")?;
                let score: f64 = row.try_get::<f64, _>("bm25_score")?;
                
                // Normalize BM25 score: negative → [0, 1]
                // BM25 returns scores in range roughly [-10, 0]
                // Use exp(score) to convert to [0, 1]
                let normalized = (score as f32).exp();
                let clamped = normalized.clamp(0.0, 1.0);
                
                results.push((id, clamped));
                
                if results.len() >= limit {
                    break;
                }
            }

            Ok(results)
        })
    }

    fn search_fuzzy(
        &self,
        _query: &str,
        _scope_filter: Option<&str>,
        _limit: usize,
        _threshold: f32,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, f32)>>> + Send + '_>> {
        Box::pin(async move {
            Ok(vec![])
        })
    }

    fn search_ann(
        &self,
        embedding: Vec<f32>,
        limit: usize,
        scope_filter: Option<&str>,
        type_filter: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, f32)>>> + Send + '_>> {
        let pool = self.pool.clone();
        let scope_filter = scope_filter.map(|s| s.to_string());
        let type_filter = type_filter.map(|s| s.to_string());

        Box::pin(async move {
            // For now, use a simpler approach: query all memories with embeddings 
            // and compute similarity client-side
            // TODO: Replace with proper sqlite-vec ANN when extension is stable
            
            let mut sql = r#"
                SELECT m.id, m.importance, v.embedding
                FROM vec_memories v
                JOIN memories m ON v.memory_id = m.id
                WHERE 1=1
            "#.to_string();

            if type_filter.is_some() {
                sql.push_str(" AND m.type = ?");
            }

            if scope_filter.is_some() {
                sql.push_str(" AND EXISTS (SELECT 1 FROM memory_scopes WHERE memory_id = m.id AND scope LIKE ? || '%')");
            }

            sql.push_str(&format!(" LIMIT {}", limit * 2)); // Over-fetch for reranking

            let mut query_builder = sqlx::query_as::<_, (String, i64, Vec<u8>)>(&sql);

            if let Some(ref type_) = type_filter {
                query_builder = query_builder.bind(type_);
            }

            if let Some(ref scope) = scope_filter {
                query_builder = query_builder.bind(scope);
            }

            let rows = query_builder.fetch_all(&pool).await.unwrap_or_default();

            // Compute cosine similarity for each row
            let mut scored_results: Vec<(String, f32)> = rows.into_iter().filter_map(|(id, _importance, embedding_bytes)| {
                // Convert bytes back to f32 vector
                if embedding_bytes.len() % 4 != 0 {
                    return None;
                }
                
                let mut stored_vec = Vec::with_capacity(embedding_bytes.len() / 4);
                for chunk in embedding_bytes.chunks(4) {
                    if let Ok(bytes) = <[u8; 4]>::try_from(chunk) {
                        stored_vec.push(f32::from_le_bytes(bytes));
                    }
                }

                // Compute cosine similarity
                if stored_vec.len() != embedding.len() {
                    return None;
                }

                let dot_product: f32 = embedding.iter().zip(&stored_vec).map(|(a, b)| a * b).sum();
                let query_norm: f32 = embedding.iter().map(|x| x * x).sum::<f32>().sqrt();
                let stored_norm: f32 = stored_vec.iter().map(|x| x * x).sum::<f32>().sqrt();

                if query_norm < 1e-10 || stored_norm < 1e-10 {
                    return Some((id, 0.0));
                }

                let similarity = dot_product / (query_norm * stored_norm);
                let normalized = (similarity + 1.0) / 2.0; // Convert [-1, 1] to [0, 1]

                Some((id, normalized.clamp(0.0, 1.0)))
            }).collect();

            // Sort by similarity descending
            scored_results.sort_by(|a, b| {
                b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal)
            });

            scored_results.truncate(limit);
            Ok(scored_results)
        })
    }

    fn fetch_memories_raw(
        &self,
        _scope_filter: Option<&str>,
        _type_filter: Option<&str>,
        _limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, String)>>> + Send + '_>> {
        Box::pin(async move {
            Ok(vec![])
        })
    }

    fn fetch_memories_for_chunking(
        &self,
        limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, String, String)>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let memories: Vec<(String, String, String)> = sqlx::query_as(
                "SELECT id, content, created_at FROM memories \
                 ORDER BY created_at DESC \
                 LIMIT ?"
            )
            .bind(limit as i32)
            .fetch_all(&pool)
            .await?;
            Ok(memories)
        })
    }

    fn search_hybrid(
        &self,
        opts: Value,
        _model_name: &str,
        _embeddings_enabled: bool,
        _config_min_score: f32,
        _config_search: &Value,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        Box::pin(async move {
            Ok(json!({"results": []}))
        })
    }

    // ===== Ontology =====

    fn add_concept(
        &self,
        name: &str,
        description: Option<&str>,
        scope: Option<&str>,
        id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let name = name.to_string();
        let description = description.map(|s| s.to_string());
        let scope = scope.map(|s| s.to_string());
        let id = id.map(|s| s.to_string()).unwrap_or_else(|| Uuid::new_v4().to_string());
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            sqlx::query(
                "INSERT OR REPLACE INTO ontology_concepts (id, name, description, scope, created_at) VALUES (?, ?, ?, ?, ?)",
            )
            .bind(&id)
            .bind(&name)
            .bind(&description)
            .bind(&scope)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to add concept")?;

            Ok(json!({"id": id, "name": name}))
        })
    }

    fn get_concept(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let row = sqlx::query(
                "SELECT id, name, description, scope FROM ontology_concepts WHERE id = ? OR id LIKE ? LIMIT 1",
            )
            .bind(&id)
            .bind(format!("{}%", id))
            .fetch_optional(&pool)
            .await
            .context("Failed to fetch concept")?;

            row.map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "name": r.get::<String, _>("name"),
                    "description": r.get::<Option<String>, _>("description"),
                    "scope": r.get::<Option<String>, _>("scope")
                })
            })
            .context("Concept not found")
        })
    }

    fn get_concept_with_instances(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        self.get_concept(id)
    }

    fn list_concepts(&self, _scope: Option<&str>, limit: usize) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query("SELECT id, name, description, scope, created_at FROM ontology_concepts LIMIT ?")
                .bind(limit as i64)
                .fetch_all(&pool)
                .await
                .context("Failed to list concepts")?;

            Ok(rows.iter().map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "name": r.get::<String, _>("name"),
                    "description": r.get::<Option<String>, _>("description"),
                    "scope": r.get::<Option<String>, _>("scope"),
                    "created_at": r.get::<String, _>("created_at")
                })
            }).collect())
        })
    }

    fn delete_concept(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let result = sqlx::query("DELETE FROM ontology_concepts WHERE id = ? OR id LIKE ?")
                .bind(&id)
                .bind(format!("{}%", id))
                .execute(&pool)
                .await
                .context("Failed to delete concept")?;

            Ok(result.rows_affected() > 0)
        })
    }

    fn resolve_concept_id(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<String>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let row = sqlx::query_scalar::<_, String>("SELECT id FROM ontology_concepts WHERE id LIKE ? LIMIT 1")
                .bind(format!("{}%", id))
                .fetch_optional(&pool)
                .await
                .context("Failed to resolve concept ID")?;

            row.context("Concept not found")
        })
    }

    fn search_concepts(
        &self,
        _query: &str,
        _scope: Option<&str>,
        limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        self.list_concepts(None, limit)
    }

    fn add_ontology_edge(
        &self,
        from_id: &str,
        _from_kind: &str,
        rel: &str,
        to_id: &str,
        _to_kind: &str,
        note: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let rel = rel.to_string();
        let to_id = to_id.to_string();
        let note = note.map(|s| s.to_string());
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            sqlx::query(
                "INSERT INTO ontology_edges (from_id, from_type, rel_type, to_id, to_type, note, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            )
            .bind(&from_id)
            .bind("concept")
            .bind(&rel)
            .bind(&to_id)
            .bind("concept")
            .bind(&note)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to add ontology edge")?;

            Ok(json!({"from_id": from_id, "rel_type": rel, "to_id": to_id}))
        })
    }

    fn delete_ontology_edge(&self, edge_id: i64) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let result = sqlx::query("DELETE FROM ontology_edges WHERE id = ?")
                .bind(edge_id)
                .execute(&pool)
                .await
                .context("Failed to delete ontology edge")?;

            Ok(result.rows_affected() > 0)
        })
    }

    // ===== Graph Stubs =====

    fn query_cypher(&self, _query: &str, _params: &Value) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        Box::pin(async move {
            anyhow::bail!("Cypher not supported on SQLite backend")
        })
    }

    fn get_neighbors(&self, _id: &str, _depth: usize) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        Box::pin(async move {
            anyhow::bail!("Graph traversal not fully supported on SQLite backend")
        })
    }

    fn check_model_mismatch(&self, _configured_model: &str) -> Pin<Box<dyn Future<Output = Result<Option<(String, String)>>> + Send + '_>> {
        Box::pin(async move {
            Ok(None)
        })
    }

    fn shutdown(&self) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            // Synchronous flush for SQLite
            sqlx::query("PRAGMA synchronous = FULL")
                .execute(&pool)
                .await?;
            // WAL checkpoint to ensure durability
            sqlx::query("PRAGMA wal_checkpoint(RESTART)")
                .execute(&pool)
                .await?;
            Ok(())
        })
    }

    fn delete_chunks_for_memory(
        &self,
        _memory_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<usize>> + Send + '_>> {
        Box::pin(async move {
            // SQLite doesn't store chunks (computed on-demand)
            // This is a no-op for SQLite, Neo4j will implement chunk deletion
            Ok(0)
        })
    }

    fn fetch_chunks(
        &self,
        _limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, String, String)>>> + Send + '_>> {
        Box::pin(async move {
            // SQLite doesn't store chunks
            // Chunks are computed on-demand from memories
            Ok(vec![])
        })
    }

    fn store_chunk_embedding(
        &self,
        chunk_id: String,
        _memory_id: String,
        embedding: Vec<f32>,
    ) -> Pin<Box<dyn Future<Output = Result<(String, usize)>> + Send + '_>> {
        let pool = self.pool.clone();
        let dim = embedding.len();

        Box::pin(async move {
            // SQLite with sqlite-vector extension
            // Store embedding as f32 vector directly
            let embedding_bytes: Vec<u8> = embedding
                .iter()
                .flat_map(|f| f.to_le_bytes().to_vec())
                .collect();

            let result = sqlx::query(
                "UPDATE memory_chunks 
                 SET embedding = ?1, embedding_dim = ?2 
                 WHERE id = ?3"
            )
            .bind(&embedding_bytes)
            .bind(dim as i32)
            .bind(&chunk_id)
            .execute(&pool)
            .await;

            match result {
                Ok(_) => {
                    tracing::debug!("SQLite: Stored {}D embedding for chunk {}", dim, chunk_id);
                    Ok((chunk_id, dim))
                }
                Err(e) => {
                    tracing::warn!("SQLite: Failed to store embedding: {}", e);
                    Ok((chunk_id, 0))
                }
            }
        })
    }

    fn get_chunk_embedding(
        &self,
        chunk_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<Option<Vec<f32>>>> + Send + '_>> {
        let pool = self.pool.clone();
        let chunk_id = chunk_id.to_string();

        Box::pin(async move {
            let result: Option<(Vec<u8>, i32)> = sqlx::query_as(
                "SELECT embedding, embedding_dim FROM memory_chunks WHERE id = ?1"
            )
            .bind(&chunk_id)
            .fetch_optional(&pool)
            .await
            .ok()
            .flatten();

            if let Some((embedding_bytes, dim)) = result {
                let dim = dim as usize;
                let mut embedding = Vec::with_capacity(dim);
                
                for i in 0..dim {
                    let start = i * 4;
                    let end = start + 4;
                    if end <= embedding_bytes.len() {
                        let bytes = [
                            embedding_bytes[start],
                            embedding_bytes[start + 1],
                            embedding_bytes[start + 2],
                            embedding_bytes[start + 3],
                        ];
                        embedding.push(f32::from_le_bytes(bytes));
                    }
                }
                
                if embedding.len() == dim {
                    return Ok(Some(embedding));
                }
            }

            Ok(None)
        })
    }

    fn search_by_embedding(
        &self,
        query_embedding: Vec<f32>,
        limit: usize,
        min_similarity: f32,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, f32)>>> + Send + '_>> {
        let pool = self.pool.clone();
        let dim = query_embedding.len();

        Box::pin(async move {
            // SQLite with sqlite-vector: use vector distance operations
            // Fetch all chunks with embeddings
            let chunks: Vec<(String, Vec<u8>, i32)> = sqlx::query_as(
                "SELECT id, embedding, embedding_dim FROM memory_chunks 
                 WHERE embedding IS NOT NULL AND embedding_dim = ?1
                 LIMIT 10000"
            )
            .bind(dim as i32)
            .fetch_all(&pool)
            .await
            .unwrap_or_default();

            let mut similarities = Vec::new();
            
            for (chunk_id, embedding_bytes, d) in chunks {
                let d = d as usize;
                if d != dim {
                    continue;
                }
                
                let mut embedding = Vec::with_capacity(dim);
                for i in 0..dim {
                    let start = i * 4;
                    let end = start + 4;
                    if end <= embedding_bytes.len() {
                        let bytes = [
                            embedding_bytes[start],
                            embedding_bytes[start + 1],
                            embedding_bytes[start + 2],
                            embedding_bytes[start + 3],
                        ];
                        embedding.push(f32::from_le_bytes(bytes));
                    }
                }
                
                if embedding.len() == dim {
                    if let Ok(similarity) = voidm_core::similarity::cosine_similarity(&query_embedding, &embedding) {
                        if similarity >= min_similarity {
                            similarities.push((chunk_id, similarity));
                        }
                    }
                }
            }

            // Sort by similarity descending
            similarities.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
            similarities.truncate(limit);

            tracing::debug!("SQLite: Found {} similar chunks (cosine)", similarities.len());
            Ok(similarities)
        })
    }

    fn export_to_jsonl(
        &self,
        limit: Option<usize>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<String>>> + Send + '_>> {
        let pool = self.pool.clone();

        Box::pin(async move {
            let mut records = Vec::new();
            let limit_val = limit.unwrap_or(999999) as i64;

            // Fetch all memories
            let memories: Vec<(String, String, String, String, String)> = 
                sqlx::query_as(
                    "SELECT id, type, content, created_at, updated_at FROM memories LIMIT ?"
                )
                .bind(limit_val)
                .fetch_all(&pool)
                .await
                .unwrap_or_default();

            for (id, mem_type, content, created_at, updated_at) in memories {
                let memory_record = voidm_core::export::MemoryRecord {
                    id: id.clone(),
                    content,
                    memory_type: mem_type,
                    created_at,
                    updated_at: Some(updated_at),
                    scope: None,
                    tags: None,
                    provenance: None,
                    context: None,
                    importance: None,
                    quality_score: None,
                };

                let record = voidm_core::export::ExportRecord::Memory(memory_record);
                if let Ok(json) = voidm_core::export::record_to_jsonl(&record) {
                    records.push(json);
                }
            }

            tracing::info!("SQLite: Exported {} memory records", records.len());
            Ok(records)
        })
    }

    fn import_from_jsonl(
        &self,
        records: Vec<String>,
    ) -> Pin<Box<dyn Future<Output = Result<(usize, usize, usize)>> + Send + '_>> {
        let pool = self.pool.clone();

        Box::pin(async move {
            let mut memory_count = 0;
            let mut chunk_count = 0;
            let mut relationship_count = 0;

            for line in records {
                if line.trim().is_empty() {
                    continue;
                }

                match serde_json::from_str::<voidm_core::export::ExportRecord>(&line) {
                    Ok(voidm_core::export::ExportRecord::Memory(mem)) => {
                        // Insert memory
                        let result = sqlx::query(
                            "INSERT OR IGNORE INTO memories (id, type, content, created_at, updated_at) 
                             VALUES (?, ?, ?, ?, ?)"
                        )
                        .bind(&mem.id)
                        .bind(&mem.memory_type)
                        .bind(&mem.content)
                        .bind(&mem.created_at)
                        .bind(mem.updated_at.as_deref().unwrap_or(&mem.created_at))
                        .execute(&pool)
                        .await;

                        if result.is_ok() {
                            memory_count += 1;
                        }
                    }
                    Ok(voidm_core::export::ExportRecord::MemoryChunk(_chunk)) => {
                        // TODO: Implement chunk import
                        chunk_count += 1;
                    }
                    Ok(voidm_core::export::ExportRecord::Relationship(_rel)) => {
                        // TODO: Implement relationship import
                        relationship_count += 1;
                    }
                    Ok(voidm_core::export::ExportRecord::Concept(_concept)) => {
                        // Concepts not yet supported in SQLite
                    }
                    Err(_) => {
                        // Skip malformed records
                        continue;
                    }
                }
            }

            tracing::info!(
                "SQLite: Imported {} memories, {} chunks, {} relationships",
                memory_count, chunk_count, relationship_count
            );
            Ok((memory_count, chunk_count, relationship_count))
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_health_check() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        assert!(db.health_check().await.is_ok());
    }

    #[tokio::test]
    async fn test_schema_creation() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        assert!(db.ensure_schema().await.is_ok());
    }

    #[tokio::test]
    async fn test_add_and_get_memory() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        db.ensure_schema().await.unwrap();

        let req = json!({
            "content": "test memory",
            "type": "semantic",
            "importance": 5,
            "tags": ["test"],
            "scopes": ["global"]
        });

        let resp = db.add_memory(req, &json!({})).await.unwrap();
        let id = resp.get("id").and_then(|v| v.as_str()).unwrap();

        let mem = db.get_memory(id).await.unwrap();
        assert!(mem.is_some());
        let m = mem.unwrap();
        assert_eq!(m["content"], "test memory");
        assert_eq!(m["type"], "semantic");
    }

    #[tokio::test]
    async fn test_list_memories() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        db.ensure_schema().await.unwrap();

        db.add_memory(
            json!({"content": "mem1", "type": "semantic"}),
            &json!({}),
        )
        .await
        .unwrap();

        db.add_memory(
            json!({"content": "mem2", "type": "episodic"}),
            &json!({}),
        )
        .await
        .unwrap();

        let list = db.list_memories(None).await.unwrap();
        assert_eq!(list.len(), 2);
    }
}
