//! SQLite backend for voidm using the generic Database trait
//!
//! This crate provides a lightweight SQLite backend implementation
//! that uses the QueryTranslator abstraction from voidm-core for all SQL generation.
//!
//! Key pattern: JSON ↔ CypherOperation ↔ SQL Translation
//! - Incoming JSON trait calls converted to CypherOperation
//! - SqliteTranslator generates backend-specific SQL
//! - Results converted back to JSON for trait consumers

use anyhow::{Context, Result};
use chrono::Utc;
use once_cell::sync::OnceCell;
use serde_json::{json, Value};
use sqlx::sqlite::{SqliteConnectOptions, SqlitePool, SqlitePoolOptions, SqliteRow};
use sqlx::{FromRow, Row};
use std::path::Path;
use std::pin::Pin;
use std::future::Future;
use std::str::FromStr;
use uuid::Uuid;
use voidm_db_trait::Database;
use voidm_core::query::translator::QueryTranslator;
use voidm_core::query::sqlite::SqliteTranslator;
use voidm_core::query::cypher::CypherOperation;

/// Load sqlite-vec at process level via sqlite3_auto_extension
fn ensure_sqlite_vec_loaded() {
    static LOADED: OnceCell<()> = OnceCell::new();
    LOADED.get_or_init(|| unsafe {
        libsqlite3_sys::sqlite3_auto_extension(Some(std::mem::transmute(
            sqlite_vec::sqlite3_vec_init as *const (),
        )));
    });
}

/// Open or create SQLite connection pool
pub async fn open_pool(db_path: &Path) -> Result<SqlitePool> {
    ensure_sqlite_vec_loaded();

    if let Some(parent) = db_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Cannot create directory {}", parent.display()))?;
    }

    let url = format!("sqlite://{}?mode=rwc", db_path.display());
    let opts = SqliteConnectOptions::from_str(&url)?
        .journal_mode(sqlx::sqlite::SqliteJournalMode::Wal)
        .foreign_keys(true)
        .create_if_missing(true);

    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect_with(opts)
        .await
        .with_context(|| format!("Cannot open database at {}", db_path.display()))?;

    Ok(pool)
}

/// SQLite database backend using generic Database trait
#[derive(Clone)]
pub struct SqliteDatabase {
    pub pool: SqlitePool,
}

impl SqliteDatabase {
    /// Create new instance with existing pool
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    /// Get the query translator
    fn translator() -> SqliteTranslator {
        SqliteTranslator
    }

    /// Execute a query generated by translator and map to JSON
    async fn execute_and_map<F>(
        &self,
        sql: &str,
        params: &voidm_core::query::QueryParams,
        map_fn: F,
    ) -> Result<Value>
    where
        F: Fn(&SqliteRow) -> Value,
    {
        // This is a simplified version - full implementation would use sqlx bind parameters
        let row = sqlx::query(sql)
            .fetch_optional(&self.pool)
            .await
            .context("Query execution failed")?;

        Ok(row.map(|r| map_fn(&r)).unwrap_or(Value::Null))
    }
}

impl Database for SqliteDatabase {
    fn health_check(&self) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            sqlx::query("SELECT 1").execute(&pool).await?;
            Ok(())
        })
    }

    fn close(&self) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            pool.close().await;
            Ok(())
        })
    }

    fn ensure_schema(&self) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            // Create memories table
            sqlx::query(
                r#"
                CREATE TABLE IF NOT EXISTS memories (
                    id TEXT PRIMARY KEY,
                    type TEXT NOT NULL,
                    content TEXT NOT NULL,
                    importance INTEGER DEFAULT 5,
                    tags TEXT DEFAULT '[]',
                    scopes TEXT DEFAULT '[]',
                    metadata TEXT DEFAULT '{}',
                    quality_score REAL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )
                "#,
            )
            .execute(&pool)
            .await
            .ok();

            // Create edges table
            sqlx::query(
                r#"
                CREATE TABLE IF NOT EXISTS memory_edges (
                    id TEXT PRIMARY KEY,
                    from_id TEXT NOT NULL,
                    rel_type TEXT NOT NULL,
                    to_id TEXT NOT NULL,
                    note TEXT,
                    created_at TEXT NOT NULL
                )
                "#,
            )
            .execute(&pool)
            .await
            .ok();

            // Create ontology tables
            sqlx::query(
                r#"
                CREATE TABLE IF NOT EXISTS ontology_concepts (
                    id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    description TEXT,
                    scope TEXT,
                    created_at TEXT NOT NULL
                )
                "#,
            )
            .execute(&pool)
            .await
            .ok();

            sqlx::query(
                r#"
                CREATE TABLE IF NOT EXISTS ontology_edges (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    from_id TEXT NOT NULL,
                    from_kind TEXT NOT NULL,
                    rel_type TEXT NOT NULL,
                    to_id TEXT NOT NULL,
                    to_kind TEXT NOT NULL,
                    note TEXT,
                    created_at TEXT NOT NULL
                )
                "#,
            )
            .execute(&pool)
            .await
            .ok();

            Ok(())
        })
    }

    fn add_memory(
        &self,
        req_json: Value,
        _config: &Value,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let id = Uuid::new_v4().to_string();
            let now = Utc::now().to_rfc3339();
            
            let content = req_json
                .get("content")
                .and_then(|v| v.as_str())
                .context("Missing content")?;
            let memory_type = req_json
                .get("type")
                .and_then(|v| v.as_str())
                .or_else(|| req_json.get("memory_type").and_then(|v| v.as_str()))
                .context("Missing type/memory_type")?;
            let importance = req_json
                .get("importance")
                .and_then(|v| v.as_i64())
                .unwrap_or(5) as i32;
            let tags = req_json
                .get("tags")
                .map(|v| v.to_string())
                .unwrap_or_else(|| "[]".to_string());
            let scopes = req_json
                .get("scopes")
                .map(|v| v.to_string())
                .unwrap_or_else(|| "[]".to_string());
            let metadata = req_json
                .get("metadata")
                .map(|v| v.to_string())
                .unwrap_or_else(|| "{}".to_string());

            sqlx::query(
                r#"
                INSERT INTO memories 
                (id, type, content, importance, tags, scopes, metadata, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                "#,
            )
            .bind(&id)
            .bind(memory_type)
            .bind(content)
            .bind(importance)
            .bind(&tags)
            .bind(&scopes)
            .bind(&metadata)
            .bind(&now)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to insert memory")?;

            Ok(json!({
                "id": id,
                "conflicts": [],
                "duplicate_warnings": [],
                "suggested_links": []
            }))
        })
    }

    fn get_memory(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<Option<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let row = sqlx::query(
                "SELECT id, type, content, importance, tags, scopes, metadata, created_at, updated_at FROM memories WHERE id = ? OR id LIKE ? LIMIT 1",
            )
            .bind(&id)
            .bind(format!("{}%", id))
            .fetch_optional(&pool)
            .await
            .context("Failed to fetch memory")?;

            Ok(row.map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "type": r.get::<String, _>("type"),
                    "content": r.get::<String, _>("content"),
                    "importance": r.get::<i32, _>("importance"),
                    "tags": serde_json::from_str::<Value>(&r.get::<String, _>("tags")).unwrap_or(Value::Array(vec![])),
                    "scopes": serde_json::from_str::<Value>(&r.get::<String, _>("scopes")).unwrap_or(Value::Array(vec![])),
                    "metadata": serde_json::from_str::<Value>(&r.get::<String, _>("metadata")).unwrap_or(Value::Object(Default::default())),
                    "created_at": r.get::<String, _>("created_at"),
                    "updated_at": r.get::<String, _>("updated_at")
                })
            }))
        })
    }

    fn list_memories(
        &self,
        limit: Option<usize>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let limit = limit.unwrap_or(100) as i64;
            let rows = sqlx::query(
                "SELECT id, type, content, importance, tags, scopes, metadata, created_at, updated_at FROM memories ORDER BY created_at DESC LIMIT ?",
            )
            .bind(limit)
            .fetch_all(&pool)
            .await
            .context("Failed to fetch memories")?;

            Ok(rows.iter().map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "type": r.get::<String, _>("type"),
                    "content": r.get::<String, _>("content"),
                    "importance": r.get::<i32, _>("importance"),
                    "tags": serde_json::from_str::<Value>(&r.get::<String, _>("tags")).unwrap_or(Value::Array(vec![])),
                    "scopes": serde_json::from_str::<Value>(&r.get::<String, _>("scopes")).unwrap_or(Value::Array(vec![])),
                    "metadata": serde_json::from_str::<Value>(&r.get::<String, _>("metadata")).unwrap_or(Value::Object(Default::default())),
                    "created_at": r.get::<String, _>("created_at"),
                    "updated_at": r.get::<String, _>("updated_at")
                })
            }).collect())
        })
    }

    fn delete_memory(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let result = sqlx::query("DELETE FROM memories WHERE id = ? OR id LIKE ?")
                .bind(&id)
                .bind(format!("{}%", id))
                .execute(&pool)
                .await
                .context("Failed to delete memory")?;

            Ok(result.rows_affected() > 0)
        })
    }

    fn update_memory(
        &self,
        id: &str,
        content: &str,
    ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        let content = content.to_string();
        Box::pin(async move {
            let now = Utc::now().to_rfc3339();
            sqlx::query("UPDATE memories SET content = ?, updated_at = ? WHERE id = ? OR id LIKE ?")
                .bind(&content)
                .bind(&now)
                .bind(&id)
                .bind(format!("{}%", id))
                .execute(&pool)
                .await
                .context("Failed to update memory")?;
            Ok(())
        })
    }

    fn resolve_memory_id(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<String>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            if id.len() < 4 {
                anyhow::bail!("ID prefix too short");
            }
            let row = sqlx::query_scalar::<_, String>("SELECT id FROM memories WHERE id LIKE ? LIMIT 1")
                .bind(format!("{}%", id))
                .fetch_optional(&pool)
                .await
                .context("Failed to resolve ID")?;

            row.context("ID not found")
        })
    }

    fn list_scopes(&self) -> Pin<Box<dyn Future<Output = Result<Vec<String>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query_scalar::<_, String>(
                "SELECT DISTINCT scope FROM (SELECT json_each.value as scope FROM memories, json_each(memories.scopes))"
            )
            .fetch_all(&pool)
            .await
            .unwrap_or_default();
            Ok(rows)
        })
    }

    // ===== Memory Edges =====

    fn link_memories(
        &self,
        from_id: &str,
        rel: &str,
        to_id: &str,
        note: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let rel = rel.to_string();
        let to_id = to_id.to_string();
        let note = note.map(|s| s.to_string());
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            let id = Uuid::new_v4().to_string();
            sqlx::query(
                "INSERT OR REPLACE INTO memory_edges (id, from_id, rel_type, to_id, note, created_at) VALUES (?, ?, ?, ?, ?, ?)",
            )
            .bind(&id)
            .bind(&from_id)
            .bind(&rel)
            .bind(&to_id)
            .bind(&note)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to link memories")?;

            Ok(json!({"edge_id": id, "from_id": from_id, "rel_type": rel, "to_id": to_id}))
        })
    }

    fn unlink_memories(
        &self,
        from_id: &str,
        rel: &str,
        to_id: &str,
    ) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let rel = rel.to_string();
        let to_id = to_id.to_string();

        Box::pin(async move {
            let result = sqlx::query("DELETE FROM memory_edges WHERE from_id = ? AND rel_type = ? AND to_id = ?")
                .bind(&from_id)
                .bind(&rel)
                .bind(&to_id)
                .execute(&pool)
                .await
                .context("Failed to unlink memories")?;

            Ok(result.rows_affected() > 0)
        })
    }

    fn list_edges(&self) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query("SELECT id, from_id, rel_type, to_id, note FROM memory_edges")
                .fetch_all(&pool)
                .await
                .context("Failed to list edges")?;

            Ok(rows.iter().map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "from_id": r.get::<String, _>("from_id"),
                    "rel_type": r.get::<String, _>("rel_type"),
                    "to_id": r.get::<String, _>("to_id"),
                    "note": r.get::<Option<String>, _>("note")
                })
            }).collect())
        })
    }

    fn list_ontology_edges(&self) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query("SELECT id, from_id, from_kind, rel_type, to_id, to_kind, note FROM ontology_edges")
                .fetch_all(&pool)
                .await
                .context("Failed to list ontology edges")?;

            Ok(rows.iter().map(|r| {
                json!({
                    "id": r.get::<i64, _>("id"),
                    "from_id": r.get::<String, _>("from_id"),
                    "from_kind": r.get::<String, _>("from_kind"),
                    "rel_type": r.get::<String, _>("rel_type"),
                    "to_id": r.get::<String, _>("to_id"),
                    "to_kind": r.get::<String, _>("to_kind"),
                    "note": r.get::<Option<String>, _>("note")
                })
            }).collect())
        })
    }

    fn create_ontology_edge(
        &self,
        from_id: &str,
        from_type: &str,
        rel_type: &str,
        to_id: &str,
        to_type: &str,
    ) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let from_type = from_type.to_string();
        let rel_type = rel_type.to_string();
        let to_id = to_id.to_string();
        let to_type = to_type.to_string();
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            sqlx::query(
                "INSERT INTO ontology_edges (from_id, from_kind, rel_type, to_id, to_kind, created_at) VALUES (?, ?, ?, ?, ?, ?)",
            )
            .bind(&from_id)
            .bind(&from_type)
            .bind(&rel_type)
            .bind(&to_id)
            .bind(&to_type)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to create ontology edge")?;

            Ok(true)
        })
    }

    // ===== Search Stubs (for now) =====

    fn search_bm25(
        &self,
        _query: &str,
        _scope_filter: Option<&str>,
        _type_filter: Option<&str>,
        _limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, f32)>>> + Send + '_>> {
        Box::pin(async move {
            Ok(vec![])
        })
    }

    fn search_fuzzy(
        &self,
        _query: &str,
        _scope_filter: Option<&str>,
        _limit: usize,
        _threshold: f32,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, f32)>>> + Send + '_>> {
        Box::pin(async move {
            Ok(vec![])
        })
    }

    fn fetch_memories_raw(
        &self,
        _scope_filter: Option<&str>,
        _type_filter: Option<&str>,
        _limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<(String, String)>>> + Send + '_>> {
        Box::pin(async move {
            Ok(vec![])
        })
    }

    fn search_hybrid(
        &self,
        opts: Value,
        _model_name: &str,
        _embeddings_enabled: bool,
        _config_min_score: f32,
        _config_search: &Value,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        Box::pin(async move {
            Ok(json!({"results": []}))
        })
    }

    // ===== Ontology =====

    fn add_concept(
        &self,
        name: &str,
        description: Option<&str>,
        scope: Option<&str>,
        id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let name = name.to_string();
        let description = description.map(|s| s.to_string());
        let scope = scope.map(|s| s.to_string());
        let id = id.map(|s| s.to_string()).unwrap_or_else(|| Uuid::new_v4().to_string());
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            sqlx::query(
                "INSERT OR REPLACE INTO ontology_concepts (id, name, description, scope, created_at) VALUES (?, ?, ?, ?, ?)",
            )
            .bind(&id)
            .bind(&name)
            .bind(&description)
            .bind(&scope)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to add concept")?;

            Ok(json!({"id": id, "name": name}))
        })
    }

    fn get_concept(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let row = sqlx::query(
                "SELECT id, name, description, scope FROM ontology_concepts WHERE id = ? OR id LIKE ? LIMIT 1",
            )
            .bind(&id)
            .bind(format!("{}%", id))
            .fetch_optional(&pool)
            .await
            .context("Failed to fetch concept")?;

            row.map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "name": r.get::<String, _>("name"),
                    "description": r.get::<Option<String>, _>("description"),
                    "scope": r.get::<Option<String>, _>("scope")
                })
            })
            .context("Concept not found")
        })
    }

    fn get_concept_with_instances(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        self.get_concept(id)
    }

    fn list_concepts(&self, _scope: Option<&str>, limit: usize) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let rows = sqlx::query("SELECT id, name, description, scope FROM ontology_concepts LIMIT ?")
                .bind(limit as i64)
                .fetch_all(&pool)
                .await
                .context("Failed to list concepts")?;

            Ok(rows.iter().map(|r| {
                json!({
                    "id": r.get::<String, _>("id"),
                    "name": r.get::<String, _>("name"),
                    "description": r.get::<Option<String>, _>("description"),
                    "scope": r.get::<Option<String>, _>("scope")
                })
            }).collect())
        })
    }

    fn delete_concept(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let result = sqlx::query("DELETE FROM ontology_concepts WHERE id = ? OR id LIKE ?")
                .bind(&id)
                .bind(format!("{}%", id))
                .execute(&pool)
                .await
                .context("Failed to delete concept")?;

            Ok(result.rows_affected() > 0)
        })
    }

    fn resolve_concept_id(&self, id: &str) -> Pin<Box<dyn Future<Output = Result<String>> + Send + '_>> {
        let pool = self.pool.clone();
        let id = id.to_string();
        Box::pin(async move {
            let row = sqlx::query_scalar::<_, String>("SELECT id FROM ontology_concepts WHERE id LIKE ? LIMIT 1")
                .bind(format!("{}%", id))
                .fetch_optional(&pool)
                .await
                .context("Failed to resolve concept ID")?;

            row.context("Concept not found")
        })
    }

    fn search_concepts(
        &self,
        _query: &str,
        _scope: Option<&str>,
        limit: usize,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Value>>> + Send + '_>> {
        self.list_concepts(None, limit)
    }

    fn add_ontology_edge(
        &self,
        from_id: &str,
        _from_kind: &str,
        rel: &str,
        to_id: &str,
        _to_kind: &str,
        note: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        let pool = self.pool.clone();
        let from_id = from_id.to_string();
        let rel = rel.to_string();
        let to_id = to_id.to_string();
        let note = note.map(|s| s.to_string());
        let now = Utc::now().to_rfc3339();

        Box::pin(async move {
            sqlx::query(
                "INSERT INTO ontology_edges (from_id, from_kind, rel_type, to_id, to_kind, note, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            )
            .bind(&from_id)
            .bind("concept")
            .bind(&rel)
            .bind(&to_id)
            .bind("concept")
            .bind(&note)
            .bind(&now)
            .execute(&pool)
            .await
            .context("Failed to add ontology edge")?;

            Ok(json!({"from_id": from_id, "rel_type": rel, "to_id": to_id}))
        })
    }

    fn delete_ontology_edge(&self, edge_id: i64) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + '_>> {
        let pool = self.pool.clone();
        Box::pin(async move {
            let result = sqlx::query("DELETE FROM ontology_edges WHERE id = ?")
                .bind(edge_id)
                .execute(&pool)
                .await
                .context("Failed to delete ontology edge")?;

            Ok(result.rows_affected() > 0)
        })
    }

    // ===== Graph Stubs =====

    fn query_cypher(&self, _query: &str, _params: &Value) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        Box::pin(async move {
            anyhow::bail!("Cypher not supported on SQLite backend")
        })
    }

    fn get_neighbors(&self, _id: &str, _depth: usize) -> Pin<Box<dyn Future<Output = Result<Value>> + Send + '_>> {
        Box::pin(async move {
            anyhow::bail!("Graph traversal not fully supported on SQLite backend")
        })
    }

    fn check_model_mismatch(&self, _configured_model: &str) -> Pin<Box<dyn Future<Output = Result<Option<(String, String)>>> + Send + '_>> {
        Box::pin(async move {
            Ok(None)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_health_check() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        assert!(db.health_check().await.is_ok());
    }

    #[tokio::test]
    async fn test_schema_creation() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        assert!(db.ensure_schema().await.is_ok());
    }

    #[tokio::test]
    async fn test_add_and_get_memory() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        db.ensure_schema().await.unwrap();

        let req = json!({
            "content": "test memory",
            "type": "semantic",
            "importance": 5,
            "tags": ["test"],
            "scopes": ["global"]
        });

        let resp = db.add_memory(req, &json!({})).await.unwrap();
        let id = resp.get("id").and_then(|v| v.as_str()).unwrap();

        let mem = db.get_memory(id).await.unwrap();
        assert!(mem.is_some());
        let m = mem.unwrap();
        assert_eq!(m["content"], "test memory");
        assert_eq!(m["type"], "semantic");
    }

    #[tokio::test]
    async fn test_list_memories() {
        let pool = open_pool(Path::new(":memory:")).await.unwrap();
        let db = SqliteDatabase::new(pool);
        db.ensure_schema().await.unwrap();

        db.add_memory(
            json!({"content": "mem1", "type": "semantic"}),
            &json!({}),
        )
        .await
        .unwrap();

        db.add_memory(
            json!({"content": "mem2", "type": "episodic"}),
            &json!({}),
        )
        .await
        .unwrap();

        let list = db.list_memories(None).await.unwrap();
        assert_eq!(list.len(), 2);
    }
}
