use voidm_core::memory_policy::{
    RETRIEVAL_MAX_CHARS_PER_CHUNK,
    RETRIEVAL_MAX_CHUNKS,
    RETRIEVAL_MAX_CHUNKS_PER_MEMORY,
    RETRIEVAL_TOTAL_CHAR_BUDGET,
    RETRIEVAL_TOTAL_CHAR_BUDGET_PER_MEMORY,
};

#[test]
fn retrieval_policy_values_match_expected_contract() {
    assert_eq!(RETRIEVAL_MAX_CHUNKS, 6);
    assert_eq!(RETRIEVAL_MAX_CHARS_PER_CHUNK, 400);
    assert_eq!(RETRIEVAL_TOTAL_CHAR_BUDGET, 2400);
    assert_eq!(RETRIEVAL_MAX_CHUNKS_PER_MEMORY, 2);
    assert_eq!(RETRIEVAL_TOTAL_CHAR_BUDGET_PER_MEMORY, 800);
}

#[test]
fn per_memory_budget_fits_global_budget() {
    assert!(RETRIEVAL_MAX_CHUNKS_PER_MEMORY <= RETRIEVAL_MAX_CHUNKS);
    assert!(RETRIEVAL_TOTAL_CHAR_BUDGET_PER_MEMORY <= RETRIEVAL_TOTAL_CHAR_BUDGET);
    assert!(RETRIEVAL_MAX_CHUNKS_PER_MEMORY * RETRIEVAL_MAX_CHARS_PER_CHUNK >= RETRIEVAL_TOTAL_CHAR_BUDGET_PER_MEMORY);
}
